---
- name: To increase partition of c drive
  hosts: windows
  tasks:
  - win_shell: "'rescan'|diskpart"
  - win_shell: 'Resize-Partition -DriveLetter C -Size $(Get-PartitionSupportedSize -DriveLetter C).SizeMax'
